### ISSUE TITLE
Still in use?

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.sqlalchemy#13]
Is this package still actively used or can it be archived?

Cc-ing PyPI maintainers resp. contributors:

@zopyx @dataflake @zagy @jordic 

P.S.: I personally do not use it.

**Comment by dataflake** [comment]
Yes it is still in use. The last commits were about 1.5 years ago, that should be a good indicator. This package is required for Products.SQLAlchemyDA.

**Comment by icemac** [comment]
I added the `maintained` topic to this repository to make this obvious.

**Comment by icemac** [comment]
@dataflake Would you mind to cut a new release or add me as PyPI maintainer?

**Comment by ale-rt** [comment]
At Syslab we also use it pretty extensively

**Comment by dataflake** [comment]
@icemac invite sent

**Comment by zopyx** [comment]
Ufff...my package is still in use after 17 years 🥰

**Comment by icemac** [comment]
@dataflake Thank you. I just released https://pypi.org/project/z3c.sqlalchemy/2.0/.
