### ISSUE TITLE
Not compatible with SQLAlchemy 2.0

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.sqlalchemy#15]
After the release of `zope.sqlalchemy` 3.0 the tests fail here, because `zope.sqlalchemy` now supports `SQLAlchemy` 2.0 but `z3c.sqlalchemy` does not.

See https://github.com/zopefoundation/z3c.sqlalchemy/actions/runs/5235300226/jobs/9452045557 for a failed test run. (But be advised: It's not just this import error, there are more errors below it. I tried to fix them and gave up as I know too little about the necessary changes to support `SQLAlchemy` 2.0.)

Meanwhile I declared ``SQLAlchemy < 2`` on ``master``: https://github.com/zopefoundation/z3c.sqlalchemy/commit/69dd5207748722e29f6e1d87d274cb00a4a94177 and created #14 with my changes.

CCing to possible users of this package (according to #13):

@dataflake @ale-rt

**Comment by dataflake** [comment]
I have no sqlalchemy knowledge. I only did what I have to do to make Products.ZSSQLAlchemyDA work.

**Comment by ale-rt** [comment]
I can have a look

**Comment by icemac** [comment]
Released the fix for this issue in https://pypi.org/project/z3c.sqlalchemy/2.1/.
